spring:
  application:
    name: "UtBotModule"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
bot:
  token: "${BOT_TOKEN}"
  name: "${BOT_NAME}"